#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Feb 27, 2020 01:42:36 PM CET  platform: Windows NT

import tkinter as tk
import support.change_master_password_support as change_master_password_support
import view.window_util as window_util


def create_change_master_pwd_window(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = ChangeMasterPwdWindow(w)
    change_master_password_support.init(w, top, *args, **kwargs)
    return w, top


def destroy_change_master_pwd_window():
    global w
    w.destroy()
    w = None


class ChangeMasterPwdWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        
        width = 432
        height = 211
        
        center = window_util.get_center_points(top, width, height)
        
        top.geometry("{}x{}+{}+{}".format(width, height, center[0], center[1]))
        
        top.geometry("432x211+646+315")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1, 1)
        top.title("Change Master Password")
        top.configure(background="#d9d9d9")

        top.iconbitmap(window_util.get_icon_path())

        self.lblCurPwd = tk.Label(top)
        self.lblCurPwd.place(relx=0.023, rely=0.095, height=21, relwidth=0.35)
        self.lblCurPwd.configure(anchor='w')
        self.lblCurPwd.configure(background="#d9d9d9")
        self.lblCurPwd.configure(disabledforeground="#a3a3a3")
        self.lblCurPwd.configure(foreground="#000000")
        self.lblCurPwd.configure(text='''Current password:''')

        self.entCurPwd = tk.Entry(top)
        self.entCurPwd.place(relx=0.31, rely=0.095, height=21, relwidth=0.65)
        self.entCurPwd.configure(background="white")
        self.entCurPwd.configure(disabledforeground="#a3a3a3")
        self.entCurPwd.configure(font="TkFixedFont")
        self.entCurPwd.configure(foreground="#000000")
        self.entCurPwd.configure(insertbackground="black")
        self.entCurPwd.configure(show="*")

        self.lblNewPwd = tk.Label(top)
        self.lblNewPwd.place(relx=0.023, rely=0.284, height=21, relwidth=0.35)
        self.lblNewPwd.configure(activebackground="#f9f9f9")
        self.lblNewPwd.configure(activeforeground="black")
        self.lblNewPwd.configure(anchor='w')
        self.lblNewPwd.configure(background="#d9d9d9")
        self.lblNewPwd.configure(disabledforeground="#a3a3a3")
        self.lblNewPwd.configure(foreground="#000000")
        self.lblNewPwd.configure(highlightbackground="#d9d9d9")
        self.lblNewPwd.configure(highlightcolor="black")
        self.lblNewPwd.configure(text='''New password:''')

        self.entNewPwd = tk.Entry(top)
        self.entNewPwd.place(relx=0.31, rely=0.284, height=21, relwidth=0.65)
        self.entNewPwd.configure(background="white")
        self.entNewPwd.configure(disabledforeground="#a3a3a3")
        self.entNewPwd.configure(font="TkFixedFont")
        self.entNewPwd.configure(foreground="#000000")
        self.entNewPwd.configure(highlightbackground="#d9d9d9")
        self.entNewPwd.configure(highlightcolor="black")
        self.entNewPwd.configure(insertbackground="black")
        self.entNewPwd.configure(selectbackground="#c4c4c4")
        self.entNewPwd.configure(selectforeground="black")
        self.entNewPwd.configure(show="*")

        self.lblRptPwd = tk.Label(top)
        self.lblRptPwd.place(relx=0.023, rely=0.474, height=21, relwidth=0.35)
        self.lblRptPwd.configure(activebackground="#f9f9f9")
        self.lblRptPwd.configure(activeforeground="black")
        self.lblRptPwd.configure(anchor='w')
        self.lblRptPwd.configure(background="#d9d9d9")
        self.lblRptPwd.configure(disabledforeground="#a3a3a3")
        self.lblRptPwd.configure(foreground="#000000")
        self.lblRptPwd.configure(highlightbackground="#d9d9d9")
        self.lblRptPwd.configure(highlightcolor="black")
        self.lblRptPwd.configure(text='''Repeat password:''')

        self.entRptPwd = tk.Entry(top)
        self.entRptPwd.place(relx=0.31, rely=0.474, height=21, relwidth=0.65)
        self.entRptPwd.configure(background="white")
        self.entRptPwd.configure(disabledforeground="#a3a3a3")
        self.entRptPwd.configure(font="TkFixedFont")
        self.entRptPwd.configure(foreground="#000000")
        self.entRptPwd.configure(highlightbackground="#d9d9d9")
        self.entRptPwd.configure(highlightcolor="black")
        self.entRptPwd.configure(insertbackground="black")
        self.entRptPwd.configure(selectbackground="#c4c4c4")
        self.entRptPwd.configure(selectforeground="black")
        self.entRptPwd.configure(show="*")

        self.btnChange = tk.Button(top)
        self.btnChange.place(relx=0.787, rely=0.664, height=24, width=77)
        self.btnChange.configure(activebackground="#ececec")
        self.btnChange.configure(activeforeground="#000000")
        self.btnChange.configure(background="#d9d9d9")
        self.btnChange.configure(disabledforeground="#a3a3a3")
        self.btnChange.configure(foreground="#000000")
        self.btnChange.configure(highlightbackground="#d9d9d9")
        self.btnChange.configure(highlightcolor="black")
        self.btnChange.configure(pady="0")
        self.btnChange.configure(text='''Change''')

        self.btnCancel = tk.Button(top)
        self.btnCancel.place(relx=0.579, rely=0.664, height=24, width=77)
        self.btnCancel.configure(activebackground="#ececec")
        self.btnCancel.configure(activeforeground="#000000")
        self.btnCancel.configure(background="#d9d9d9")
        self.btnCancel.configure(disabledforeground="#a3a3a3")
        self.btnCancel.configure(foreground="#000000")
        self.btnCancel.configure(highlightbackground="#d9d9d9")
        self.btnCancel.configure(highlightcolor="black")
        self.btnCancel.configure(pady="0")
        self.btnCancel.configure(text='''Cancel''')

        self.lblMsg = tk.Label(top)
        self.lblMsg.place(relx=0.0, rely=0.853, height=21, width=434)
        self.lblMsg.configure(background="#d9d9d9")
        self.lblMsg.configure(disabledforeground="#a3a3a3")
        self.lblMsg.configure(foreground="#ff0000")
