#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.1
#  in conjunction with Tcl version 8.6
#    Feb 16, 2020 11:30:55 AM CET  platform: Linux

import sys
from tkinter import StringVar, OptionMenu, IntVar
import platform

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from support import entry_details_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = EntryDetailsWindow (root)
    entry_details_support.init(root, top)
    root.mainloop()

w = None
def create_EntryDetailsWindow(root, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_EntryDetailsWidnow(root, *args, **kwargs)' .'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = EntryDetailsWindow (w)
    entry_details_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_EntryDetailsWidnow():
    global w
    w.destroy()
    w = None

class EntryDetailsWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])
        
        width = 457
        height = 551
        
        center = get_center_points(width, height)
        
        top.geometry("{}x{}+{}+{}".format(width, height, center[0], center[1]))
        
        top.minsize(176, 1)
        top.maxsize(5764, 1590)
        top.resizable(1, 1)
        top.title("Entry Details")
        top.configure(highlightcolor="black")

        self.frameBody = tk.Frame(top)
        self.frameBody.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.frameBody.configure(borderwidth="2")
        self.frameBody.configure(relief="groove")
        self.frameBody.configure(background="#d9d9d9")
        self.frameBody.configure(highlightbackground="#d9d9d9")
        self.frameBody.configure(highlightcolor="black")

        self.lblType = tk.Label(self.frameBody)
        self.lblType.place(relx=0.033, rely=0.127, height=21, width=91)
        self.lblType.configure(activebackground="#f9f9f9")
        self.lblType.configure(anchor='w')
        self.lblType.configure(text='''Type:''')
        self.lblType.configure(background="#d9d9d9")
        self.lblType.configure(highlightbackground="#d9d9d9")
        self.lblType.configure(highlightcolor="black")
        
        self.selType=StringVar()
        self.typeSelMenu = OptionMenu(self.frameBody, self.selType, None)
        self.typeSelMenu.place(relx=0.219, rely=0.127,height=21, relwidth=0.6)
        self.typeSelMenu.configure(background="#d9d9d9")
        self.typeSelMenu.configure(highlightbackground="#d9d9d9")
        self.typeSelMenu.configure(highlightcolor="black")  

        self.lblCateg = tk.Label(self.frameBody)
        self.lblCateg.place(relx=0.033, rely=0.2, height=21, width=91)
        self.lblCateg.configure(activebackground="#f9f9f9")
        self.lblCateg.configure(anchor='w')
        self.lblCateg.configure(text='''Category:''')
        self.lblCateg.configure(background="#d9d9d9")
        self.lblCateg.configure(highlightbackground="#d9d9d9")
        self.lblCateg.configure(highlightcolor="black")
        
        self.selCat=StringVar()
        self.catSelMenu = OptionMenu(self.frameBody, self.selCat, None)
        self.catSelMenu.place(relx=0.219, rely=0.2,height=21, relwidth=0.6)
        self.catSelMenu.configure(background="#d9d9d9")
        self.catSelMenu.configure(highlightbackground="#d9d9d9")
        self.catSelMenu.configure(highlightcolor="black")

        self.lblName = tk.Label(self.frameBody)
        self.lblName.place(relx=0.033, rely=0.272, height=21, width=91)
        self.lblName.configure(activebackground="#f9f9f9")
        self.lblName.configure(anchor='w')
        self.lblName.configure(text='''Name:''')
        self.lblName.configure(background="#d9d9d9")
        self.lblName.configure(highlightbackground="#d9d9d9")
        self.lblName.configure(highlightcolor="black")        

        self.lblValue = tk.Label(self.frameBody)
        self.lblValue.place(relx=0.033, rely=0.345, height=21, width=91)
        self.lblValue.configure(activebackground="#f9f9f9")
        self.lblValue.configure(anchor='w')
        self.lblValue.configure(text='''Value:''')
        self.lblValue.configure(background="#d9d9d9")
        self.lblValue.configure(highlightbackground="#d9d9d9")
        self.lblValue.configure(highlightcolor="black")     

        self.lblUsername = tk.Label(self.frameBody)
        self.lblUsername.place(relx=0.033, rely=0.417, height=21, width=81)
        self.lblUsername.configure(activebackground="#f9f9f9")
        self.lblUsername.configure(anchor='w')
        self.lblUsername.configure(text='''Username:''')
        self.lblUsername.configure(background="#d9d9d9")
        self.lblUsername.configure(highlightbackground="#d9d9d9")
        self.lblUsername.configure(highlightcolor="black")          

        self.lblEmail = tk.Label(self.frameBody)
        self.lblEmail.place(relx=0.044, rely=0.544, height=21, width=80)
        self.lblEmail.configure(activebackground="#f9f9f9")
        self.lblEmail.configure(anchor='w')
        self.lblEmail.configure(text='''E-mail:''')
        self.lblEmail.configure(background="#d9d9d9")
        self.lblEmail.configure(highlightbackground="#d9d9d9")
        self.lblEmail.configure(highlightcolor="black")  

        self.lblDesc = tk.Label(self.frameBody)
        self.lblDesc.place(relx=0.044, rely=0.617, height=21, width=79)
        self.lblDesc.configure(activebackground="#f9f9f9")
        self.lblDesc.configure(anchor='w')
        self.lblDesc.configure(text='''Description:''')
        self.lblDesc.configure(background="#d9d9d9")
        self.lblDesc.configure(highlightbackground="#d9d9d9")
        self.lblDesc.configure(highlightcolor="black")          

        self.entryName = tk.Entry(self.frameBody)
        self.entryName.place(relx=0.219, rely=0.272,height=21, relwidth=0.6)
        self.entryName.configure(background="white")
        self.entryName.configure(font="TkFixedFont")
        self.entryName.configure(selectbackground="#c4c4c4")        

        self.entryValue = tk.Entry(self.frameBody)
        self.entryValue.place(relx=0.219, rely=0.345,height=21, relwidth=0.446)
        self.entryValue.configure(background="white")
        self.entryValue.configure(font="TkFixedFont")
        self.entryValue.configure(selectbackground="#c4c4c4")
        self.entryValue.configure(show="*")         

        self.entryUsername = tk.Entry(self.frameBody)
        self.entryUsername.place(relx=0.219, rely=0.417, height=21, relwidth=0.6)

        self.entryUsername.configure(background="white")
        self.entryUsername.configure(font="TkFixedFont")
        self.entryUsername.configure(selectbackground="#c4c4c4")

        self.entryEmail = tk.Entry(self.frameBody)
        self.entryEmail.place(relx=0.219, rely=0.544,height=21, relwidth=0.6)
        self.entryEmail.configure(background="white")
        self.entryEmail.configure(font="TkFixedFont")
        self.entryEmail.configure(selectbackground="#c4c4c4")

        self.textDesc = tk.Text(self.frameBody)
        self.textDesc.place(relx=0.219, rely=0.617, relheight=0.163    
                    , relwidth=0.6)
        self.textDesc.configure(background="white")
        self.textDesc.configure(font="TkTextFont")
        self.textDesc.configure(selectbackground="#c4c4c4")
        self.textDesc.configure(wrap="word")

        self.btnSave = tk.Button(self.frameBody)
        self.btnSave.place(relx=0.591, rely=0.853, height=25, width=98)
        self.btnSave.configure(activebackground="#f9f9f9")
        self.btnSave.configure(pady="0")
        self.btnSave.configure(text='''Save''')
        self.btnSave.configure(background="#d9d9d9")
        self.btnSave.configure(highlightbackground="#d9d9d9")
        self.btnSave.configure(highlightcolor="black")    

        self.btnClose = tk.Button(self.frameBody)
        self.btnClose.place(relx=0.35, rely=0.853, height=25, width=99)
        self.btnClose.configure(activebackground="#f9f9f9")
        self.btnClose.configure(pady="0")
        self.btnClose.configure(text='''Close''')
        self.btnClose.configure(background="#d9d9d9")
        self.btnClose.configure(highlightbackground="#d9d9d9")
        self.btnClose.configure(highlightcolor="black")         
        
        self.chDfEmVal=IntVar()
        self.checkDefEmail = tk.Checkbutton(self.frameBody)
        self.checkDefEmail.place(relx=0.219, rely=0.49, relheight=0.038
                , relwidth=0.442)
        self.checkDefEmail.configure(activebackground="#f9f9f9")
        self.checkDefEmail.configure(anchor='w')
        self.checkDefEmail.configure(justify='left')
        self.checkDefEmail.configure(text='''Use default e-mail''')
        self.checkDefEmail.configure(variable=self.chDfEmVal)
        self.checkDefEmail.configure(background="#d9d9d9")
        self.checkDefEmail.configure(highlightbackground="#d9d9d9")
        self.checkDefEmail.configure(highlightcolor="black")

        self.lblId = tk.Label(self.frameBody)
        self.lblId.place(relx=0.033, rely=0.054, height=21, width=92)
        self.lblId.configure(activebackground="#f9f9f9")
        self.lblId.configure(anchor='w')
        self.lblId.configure(text='''ID:''')
        self.lblId.configure(background="#d9d9d9")
        self.lblId.configure(highlightbackground="#d9d9d9")
        self.lblId.configure(highlightcolor="black")   

        self.entryId = tk.Entry(self.frameBody)
        self.entryId.place(relx=0.219, rely=0.054,height=21, relwidth=0.184)
        self.entryId.configure(background="white")
        self.entryId.configure(font="TkFixedFont")
        self.entryId.configure(selectbackground="#c4c4c4")

        self.entryModDate = tk.Entry(self.frameBody)
        self.entryModDate.place(relx=0.219, rely=0.799,height=21, relwidth=0.6)
        self.entryModDate.configure(background="white")
        self.entryModDate.configure(font="TkFixedFont")
        self.entryModDate.configure(selectbackground="#c4c4c4")

        self.lblModDate = tk.Label(self.frameBody)
        self.lblModDate.place(relx=0.044, rely=0.799, height=21, width=65)
        self.lblModDate.configure(activebackground="#f9f9f9")
        self.lblModDate.configure(anchor='w')
        self.lblModDate.configure(text='''Modified:''')
        self.lblModDate.configure(background="#d9d9d9")
        self.lblModDate.configure(highlightbackground="#d9d9d9")
        self.lblModDate.configure(highlightcolor="black")  

        self.btnDelete = tk.Button(self.frameBody)
        self.btnDelete.place(relx=0.635, rely=0.054, height=21, width=79)
        self.btnDelete.configure(activebackground="#f9f9f9")
        self.btnDelete.configure(pady="0")
        self.btnDelete.configure(text='''Delete''')
        self.btnDelete.configure(background="#d9d9d9")
        self.btnDelete.configure(highlightbackground="#d9d9d9")
        self.btnDelete.configure(highlightcolor="black") 
        
        self.btnEdit = tk.Button(self.frameBody)
        self.btnEdit.place(relx=0.438, rely=0.054, height=21, width=79)
        self.btnEdit.configure(activebackground="#f9f9f9")
        self.btnEdit.configure(pady="0")
        self.btnEdit.configure(text='''Edit''')
        self.btnEdit.configure(background="#d9d9d9")
        self.btnEdit.configure(highlightbackground="#d9d9d9")
        self.btnEdit.configure(highlightcolor="black") 

        self.btnCopyVal = tk.Button(self.frameBody)
        self.btnCopyVal.place(relx=0.832, rely=0.345, height=21, width=60)
        self.btnCopyVal.configure(activebackground="#f9f9f9")
        self.btnCopyVal.configure(pady="0")
        self.btnCopyVal.configure(text='''Copy''')
        self.btnCopyVal.configure(background="#d9d9d9")
        self.btnCopyVal.configure(highlightbackground="#d9d9d9")
        self.btnCopyVal.configure(highlightcolor="black") 

        self.btnCopyUser = tk.Button(self.frameBody)
        self.btnCopyUser.place(relx=0.832, rely=0.417, height=21, width=60)
        self.btnCopyUser.configure(activebackground="#f9f9f9")
        self.btnCopyUser.configure(pady="0")
        self.btnCopyUser.configure(text='''Copy''')
        self.btnCopyUser.configure(state='disabled')
        self.btnCopyUser.configure(background="#d9d9d9")
        self.btnCopyUser.configure(highlightbackground="#d9d9d9")
        self.btnCopyUser.configure(highlightcolor="black") 

        self.btnCopyEmail = tk.Button(self.frameBody)
        self.btnCopyEmail.place(relx=0.832, rely=0.544, height=21, width=60)
        self.btnCopyEmail.configure(activebackground="#f9f9f9")
        self.btnCopyEmail.configure(pady="0")
        self.btnCopyEmail.configure(text='''Copy''')
        self.btnCopyEmail.configure(state='disabled')
        self.btnCopyEmail.configure(background="#d9d9d9")
        self.btnCopyEmail.configure(highlightbackground="#d9d9d9")
        self.btnCopyEmail.configure(highlightcolor="black")         
        
        self.setChBtnShow=IntVar()
        self.chBtnShow = tk.Checkbutton(self.frameBody)
        self.chBtnShow.place(relx=0.678, rely=0.345, relwidth=0.133
                , relheight=0.0, height=18)
        self.chBtnShow.configure(variable=self.setChBtnShow)
        self.chBtnShow.configure(activebackground="#f9f9f9")
        self.chBtnShow.configure(anchor='w')
        self.chBtnShow.configure(justify='left')
        self.chBtnShow.configure(text='''Show''')
        self.chBtnShow.configure(background="#d9d9d9")
        self.chBtnShow.configure(highlightbackground="#d9d9d9")
        self.chBtnShow.configure(highlightcolor="black")  

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)
        
        self.lblMsg = tk.Label(self.frameBody)    
        self.lblMsg.place(relx=0.022, rely=0.935, height=18, width=436)
        self.lblMsg.configure(background="#d9d9d9")
        self.lblMsg.configure(disabledforeground="#a3a3a3")
        self.lblMsg.configure(foreground="#ff0000")    

        set_icon()
        
def get_center_points(width, height):
    center_x = int((rt.winfo_screenwidth()/2) - (width/2))
    center_y = int((rt.winfo_screenheight()/2) - (height/2))
    return (center_x, center_y)

def set_icon():
    try:
        if (platform.system() == 'Linux'):
            root.iconbitmap('@../resources/padlock.xbm')
        else:
            root.iconbitmap('../resources/padlock.ico')
    except:
        print("Unable to load logo image")