"""
Support GUI module for category details form.

Generated by PAGE version 4.26
in conjunction with Tcl version 8.6

Created on Feb 05, 2020
@author: nenad.dramicanin
"""

import model.services as services
import tkinter as tk

from model.data_model import Category


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    draw_form(args[0], args[1])


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def draw_form(action: str, category: Category):
    """Fills form with category's data and enables fields based on the 'action' parameter"""

    w.btnCancel.configure(command=destroy_window)
    w.btnSave.configure(command=lambda: on_save_btn(category))
    
    w.entId.insert(0, category.entity_id)
    w.entName.insert(0, category.name)
    w.txtDescripton.insert('1.0', category.description)
    w.entModDate.insert(0, category.modified_date)
    w.entId.configure(state="readonly")
    w.entModDate.configure(state="readonly")
    
    if action == 'info':
        w.entName.configure(state="readonly")
        w.txtDescripton.configure(state="disabled")
        w.btnSave.place_forget()


def on_save_btn(category):
    """Validates form data and initiates save action"""

    name = w.entName.get()
    description = w.txtDescripton.get("1.0", tk.END) if not w.txtDescripton.get("1.0", tk.END).isspace() else ""

    # name is mandatory field
    if name.isspace() or len(name) == 0:
        w.lblMsg.configure(text='Name can\'t be empty!')
        return
    category.name = name
    category.description = description
    services.category_edit(category)
    destroy_window()
