"""
Support GUI module for category new form.

Generated by PAGE version 4.26
in conjunction with Tcl version 8.6

Created on Feb 04, 2020
@author: nenad.dramicanin
"""
from tkinter import messagebox

import model.services as services
import tkinter as tk


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    gui.btnCreate.configure(command=on_create_btn)
    gui.btnCancel.configure(command=destroy_window)


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def on_create_btn():
    """Validates form data and initiates save action"""

    name = w.entName.get()
    description = w.txtDescripton.get("1.0", tk.END) if not w.txtDescripton.get("1.0", tk.END).isspace() else ""

    # name is mandatory field
    if name.isspace() or len(name) == 0:
        w.lblMsg.configure(text='Name can\'t be empty!')
        return

    # Check if category already exists
    if services.category_get_by_name(name) is not None:
        w.lblMsg.configure(text='Category ' + name + ' already exists!')
        return

    services.category_add(name, description)
    root.grab_set()
    messagebox.showinfo("Add category", "Category added!")
    destroy_window()
