"""
Support GUI module for entry search form.

Generated by PAGE version 4.26
in conjunction with Tcl version 8.6

Created on Feb 29, 2020
@author: nenad.dramicanin
"""

import model.data_model as data_model
import model.services as services


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    
    root.update_parent = False
    w.btnCancel.configure(command=destroy_window)
    w.btnSearch.configure(command=on_search_btn)

    # Configuring type option list
    type_menu = gui.typeSelMenu["menu"]
    type_menu.delete(0, "end")
    for val in [e.value for e in data_model.EntryType]:
        type_menu.add_command(label=val, command= lambda value=val: gui.selType.set(value))
        type_menu.configure(activebackground="#a7a7a7", background="#d9d9d9")
        type_menu.configure(foreground="#000000", activeforeground="#000000")

    # Configuring category option list
    cat_menu = gui.catSelMenu["menu"]
    cat_menu.delete(0, "end")
    for val in [c.name for c in services.category_list()]:
        cat_menu.add_command(label=val, command=lambda value=val: gui.selCat.set(value))
        cat_menu.configure(background="#d9d9d9", activebackground="#a7a7a7")
        cat_menu.configure(foreground="#000000", activeforeground="#000000")


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def on_search_btn():
    """Initiates search action based on selected/entered values"""

    search_type = w.selType.get() if w.selType.get() != "Please select" else None
    search_ctg = w.selCat.get() if w.selCat.get() != "Please select" else None
    search_name = w.entryName.get()
        
    result = services.entity_search(search_ctg, search_type, search_name)
    
    if len(result) == 0:
        w.lblMsg.configure(text="No entries found!")
    else:
        root.search_result = result
        root.update_parent = True
        destroy_window()
