#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 23, 2020 09:45:19 PM CET  platform: Windows NT

import sys
from tkinter import messagebox
from model import security
from view import main_window

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    gui.btnLogin.configure(command = on_login_btn)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def on_login_btn():
    login_pwd = w.entMasterPwd.get().replace(' ','')
    if len(login_pwd) == 0:
        messagebox.showerror('Login', 'Please enter value!')
        return
    else:
        if not security.master_pwd_valid(login_pwd):
            messagebox.showerror('Login', 'Incorrect password!')
            return
        main_window.create_MainWindow(root)
    
