#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 23, 2020 05:53:07 PM CET  platform: Windows NT

import model.security as security
import model.settings as settings
import view.login as login
import tkinter as tk
from tkinter import messagebox


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    gui.btnSubmit.configure(command=on_register_btn)


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def on_register_btn():
    global top_level
    password = w.entPwd.get().replace(' ', '')
    confirm_password = w.entRptPwd.get().replace(' ', '')
    if len(password) == 0 or len(confirm_password) == 0:
        w.lblMsg.configure(text="Please enter both values!")
        return
    if password != confirm_password:
        w.lblMsg.configure(text="Password and Confirm password are different!")
        return

    settings.init()
    security.save_master_pwd(password)
    messagebox.showinfo('Registration', 'Registration successful, please login!')

    destroy_window()
    login.create_login_window(tk.Tk())
